[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.cache]
  paths = ["node_modules", "public", "build"]

[[plugins]]
  package = "netlify-plugin-image-optim"
